data()
library("psych")  
library("dplyr")  
library("ggplot2")  
library("GGally") 
library("memisc")
library("lmtest")
library("sjPlot")
library("sgof")
library("foreign")
library("car")
library("hexbin")

library("tidyverse")
d<-cars
qplot(data=d,speed,dist)
model<-lm(data=d,dist~speed)
coef(model)
vcov(model)
summary(model)

